# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.edge.options import Options
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities


class TestNamejd:
    def setup_method(self, method):
        options = Options()
        options.add_argument("headless")
        self.driver = webdriver.Edge(options=options)
        self.vars = {}

    def teardown_method(self, method):
        self.driver.quit()

    def test_namejd(self):
        # Test name: name-jd
        # Step # | name | target | value | comment
        # 1 | open | https://workshopappjd.azurewebsites.net/ |  |
        self.driver.get("https://workshopappjd.azurewebsites.net/")
        # 2 | setWindowSize | 966x527 |  |
        self.driver.set_window_size(1000, 600)
        # 3 | click | id=name |  |
        self.driver.find_element(By.ID, "name").click()
        # 4 | type | id=name | JD |
        self.driver.find_element(By.ID, "name").send_keys("JD")
        # 5 | click | css=.btn |  |
        self.driver.find_element(By.CSS_SELECTOR, ".btn").click()
